sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gituser27/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gituser27/docker-react npm run test -- --coverage
